trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo $PACT_BROKER_URL
      echo $PACT_BROKER_TOKEN
  env:
    PACT_BROKER_URL: $(PACT_BROKER_URL)
    PACT_BROKER_TOKEN: $(PACT_BROKER_TOKEN)

- script: |
    npm i
    curl -LO https://github.com/pact-foundation/pact-provider-verifier/releases/download/v1.32.1/pact-provider-verifier-1.32.1-1-linux-x86_64.tar.gz tar xzf pact-provider-verifier-1.32.1-1-linux-x86_64.tar.gz
    npm run test:pact
  displayName: 'run consumer test'

- script: |
    npm run publish:pact
  displayName: 'consumer publish pact to the pact broker'

- script: |
    npm run verify:pact
  displayName: 'provider to verify pact from pact broker'

- script: |
    npm run create:provider:tag
  displayName: 'tag latest provider version'

- script: |
    npm run create:consumer:tag
  displayName: 'Tag latest consumer version'

- script: |
    npm run can:i:deploy:consumer
  displayName: 'Can I deploy consumer'
