trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: Docker@2
  displayName: Build the pact broker client
  inputs:
    repository:  'pactfoundation/pact-cli'
    command: build
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo $PACT_BROKER_URL
  env:
      PACT_BROKER_URL: $(PACT_BROKER_URL)
- script: |
    npm i
    npm run test:pact
  displayName: 'run consumer test'

- script: |
    npm run publish:pact
  displayName: 'consumer publish pact to the pact broker'

- script: |
    npm run verify:pact
  displayName: 'provider to verify pact from pact broker'

- script: |
    npm run create:provider:tag
  displayName: 'tag latest provider version'

- script: |
    npm run create:consumer:tag
  displayName: 'Tag latest consumer version'

- script: |
    npm run can:i:deploy:consumer
  displayName: 'Can I deploy consumer'
