trigger:
- master

# variables:
# - group: pact-demo-variables

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo $PACTBROKER
      echo $PACTBROKERURL
      echo $PACTBROKERTOKEN
  env:
    PACTBROKER: $(PACTBROKER)
    PACTBROKERURL: $(PACTBROKERURL)
    PACTBROKERTOKEN: $(PACTBROKERTOKEN)
 
- script: |
    env | sort
  displayName: 'Run a multi-line script'

- task: WhiteSource@21
  inputs:
    cwd: '$(System.DefaultWorkingDirectory)'
    projectName: 'pact-demo-js'
- task: CopyFiles@2
  inputs:
      SourceFolder: './'
      Contents: '**'
      TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'

- script: |
    npm i
    npm run test:pact
  displayName: 'run consumer test'
  env:
    PACTBROKERTOKEN: $(PACTBROKERTOKEN)

- script: |
    npm run publish:pact
  displayName: 'consumer publish pact to the pact broker'
  env:
    PACTBROKERTOKEN: $(PACTBROKERTOKEN)

- script: |
    npm run verify:pact
  displayName: 'provider to verify pact from pact broker'
  env:
    PACTBROKERTOKEN: $(PACTBROKERTOKEN)

# - script: |
#     npm run create:provider:tag
#   displayName: 'tag latest provider version'

# - script: |
#     npm run create:consumer:tag
#   displayName: 'Tag latest consumer version'

# - script: |
#     npm run can:i:deploy:consumer
#   displayName: 'Can I deploy consumer'

  
 
